export const show2208 = {
  id: 'show-22-08',
  name: 'Show 22/08',
  songIds: [
    'rock-and-roll',
    'johnny-b-goode',
    'immigrant-song',
    'gimme-all-your-loving',
    'hold-the-line',
    'you-give-love-a-bad-name',
    'it-s-a-long-way-to-the-top',
    'highway-tune',
    'safari-song',
    'money-for-nothing',
    'smoke-on-the-water',
    'livin-on-a-prayer',
    'keep-the-faith',
    'born-to-be-wild',
    'sweet-home-alabama',
    'barracuda',
    'seven-nation-army',
    'cocaine',
    'have-you-ever-seen-the-rain',
    'wicked-game',
    'even-flow',
    'welcome-to-the-jungle',
    'sweet-child-o-mine',
    'paranoid',
    'war-pigs',
    'knockin-on-heaven-s-door',
    'with-or-without-you',
    'hells-bells',
    'highway-to-hell',
    'still-loving-you',
    'separate-ways',
    'love-gun',
    'enter-sandman',
    'the-trooper',
    'rock-you-like-a-hurricane',
  ],
} as const
